### ISSUE TITLE
OPLS script doesn't work in python2 or python3

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/off-ffcompare#45]
@nthi0625 

The OPLS script you have here does not work on python2 or python3 I just called
```
python OPLS.py -h 
```
and got this warning:
```
  File "../off-ffcompare/OPLS.py", line 51
    -no_cm1a_bcc -opt -BFGS -imol2 /input_location/%s \
                                                       ^
SyntaxError: EOL while scanning string literal
```

Is the script here the one you are ACTUALLY USING? you need to have the scripts we are using to collect data on github.

head's up @vtlim

**Comment by vtlim** [comment]
fixed by #47 (culprit being the extra space after backslash)
