### ISSUE TITLE
OPLS input and behavior

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/off-ffcompare#46]
@nthi0625 and @vtlim 
I'll appologize now for not looking at this more closely sooner. 
I hadn't used the OPLS script before today, but there are a couple of other things I think it needs/should do

1. It should raise an error if the schrodinger tool directory doesn't exist, its possible that the "$SCHRODINGER/..." should actually just be an input with $SCHRODINGER as the default; since technically a user can name this directory whatever they want. 

2. I think it would be best if like in min_oe_openMM you could run both OPLS3 and OPLS2005 at the same time, is there a reason why it doesn't just do both?

**Comment by bannanc** [comment]
It should also raise an error if the input directory doesn't exist

**Comment by bannanc** [comment]
It should also not perform the minimization if the output file already exists.

**Comment by vtlim** [comment]
reasonable suggestions, fixed by #47.
but about your last comment, if output file already exists, the file could be empty so if do we want to check for this, then we should also add a check that file is not of size 0

**Comment by bannanc** [comment]
In PR #47 I addressed the follow:

1. Checks the input directory
2. Checks that the environment variable $SCHRODINGER exists
3. It can run 1 or both of 2005 or 3 based on which output directory it was given. 
4. It skips the molecule if the output file exists, but I like your option of checking the size. 

I also don't check if the input file is empty, I don't know if that is necessary or not

**Comment by bannanc** [comment]
We ended up checking if the file was empty in PR #47 so I think this can be closed.
