### ISSUE TITLE
RMSDs with multiple reference force fields

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/off-ffcompare#61]
Currently RMSD.py has the option of including multiple reference force fields. 
I think given future analysis, it would be easier if we don't act on this ability and keep different reference force fields in different files. It will make it easier to use pandas that way. 

@vtlim 
I don't know if it makes more sense to change the behavior inside RMSD.py or just make it recommended usage to only have a single force field listed for the reference.

**Comment by vtlim** [comment]
I think we should just recommend to have a single force field listed as reference. Something we should probably emphasize to Jordan is that while he's taking notes on what he does for the project, he should also include the specific command he used, especially for something in which we have variable command line arguments. That way we wouldn't have to dig through txt files to recreate the original output.

**Comment by bannanc** [comment]
Cool, I agree with all of this. I'm going to go a head and close the issue then.
